---
- name: Create user elasticsearch
  ansible.builtin.user:
    name: elasticsearch
    uid: 170

- name: Create group elasticsearch
  ansible.builtin.group:
    name: elasticsearch
    gid: 2002

- name: Delete files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/elasticsearch/my_pwd_file.tmp
    - /etc/systemd/system/elasticsearch.service.d/override.conf
...
